### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by LucioFranco** [LucioFranco/Rebound-ODM#1]
This is a tentative roadmap. No specific version targets, but the order-of-implementation is mostly accurate.
- [x] Connection Configuration Abstractions
  - [x] Node elasticsearch config
  - [x] Index and type config
- [x] Index and type model abstraction
- [x] Rebound Model -> ES schema mappings
  - [ ] Option to have strict or non strict mappings
- [x] Rebound Model CRUD
- [ ] Rebound Model Query
- [ ] Rebound Model Validation
  - [x] validate doc properties
  - [x] add default prop to schema
  - [ ] validate types
- [ ] ES Result -> Rebound Model mapping
  - [ ] Break up result from ES based on type of query
- [ ] Multi-Index, Per-Model
- [ ] Search Abstraction, with a particular focus on supporting cross-model, and cross-index searches
  - [ ] Possibly add [elastic.js](https://github.com/fullscale/elastic.js)
- [ ] Snapshot / Restore Facilities
- [ ] Migrations / Index-level Version Control
- [ ] Versioning / Document-level Version Control
